# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assgn_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assgn_app.Student')),
            ],
        ),
    ]
