# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assgn_app', '0002_studentlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('unique_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assgn_app.Professor')),
            ],
        ),
    ]
