# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assgn_app', '0004_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='prof_id',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assgn_file',
            field=models.FileField(upload_to='uploaded_files/temp'),
        ),
    ]
