# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assgn_app', '0009_auto_20160408_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenta',
            name='marks',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='assignmenta',
            name='assgn_a_file',
            field=models.FileField(upload_to='assgn_ans'),
        ),
        migrations.AlterField(
            model_name='assignmentq',
            name='assgn_q_file',
            field=models.FileField(upload_to='assgn_ques'),
        ),
    ]
