# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assgn_app', '0010_auto_20160411_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentq',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
