# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assgn_app', '0012_auto_20160413_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenta',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignmenta',
            name='assgn_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assgn_app.AssignmentQ'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmenta',
            unique_together=set([('unique_id', 'assgn_id')]),
        ),
    ]
