# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 07:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assgn_app', '0015_auto_20160415_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenta',
            name='sub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
