# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assgn_app', '0016_assignmenta_sub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
